# -*- coding: utf-8 -*-
"""zillow_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_J2ztbVOlaA4Y7cbGwDRBrnR5wmM0Ol
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Title
st.title("🏘️ Zillow Investment Dashboard")
st.write("Explore rental yields, rent growth, price trends, and top cities for real estate investment.")

# Load Data
data = pd.read_csv("/zillow_investment_data.csv")
data.columns = data.columns.str.strip()

# Check for RegionName column
if 'RegionName' not in data.columns:
    st.error("❌ 'RegionName' column not found in the dataset.")
    st.stop()

# Select a city
city = st.selectbox("📍 Select a City", data['RegionName'].unique())
city_data = data[data['RegionName'] == city].iloc[0]

# Show key metrics
st.subheader(f"📊 Metrics for {city}")
st.metric("Rental Yield", f"{city_data['rental_yield']:.2%}")
st.metric("Rent Growth (10yr)", f"{city_data['zori_10yr_growth']:.2%}")
st.metric("Price Growth (10yr)", f"{city_data['zhvi_10yr_growth']:.2%}" if 'zhvi_10yr_growth' in data.columns else "N/A")
st.metric("Investment Score", f"{city_data['investment_score']:.2f}")

# Top cities table
st.subheader("🏙️ Top 10 Investment Cities")
top_cities = data.sort_values(by='investment_score', ascending=False).head(10)
st.dataframe(top_cities[['RegionName', 'investment_score', 'rental_yield', 'zori_10yr_growth', 'zhvi_current']])

# CSV download
csv = top_cities.to_csv(index=False).encode('utf-8')
st.download_button("📥 Download Top Cities", data=csv, file_name="top_investment_cities.csv", mime="text/csv")

# Cluster plot if available
if 'cluster' in data.columns:
    st.subheader("📈 City Clusters by Growth")
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.scatterplot(data=data, x='zhvi_10yr_growth', y='zori_10yr_growth', hue='cluster', palette='tab10', ax=ax)
    plt.xlabel("ZHVI Growth (10yr)")
    plt.ylabel("ZORI Growth (10yr)")
    plt.title("City Clustering")
    st.pyplot(fig)